### ISSUE TITLE
HMAC validation failed

### ISSUE THREAD

**Issue by RoadToCode822** [Shopify/shopify-node-app#131] opened 2018-08-29 05:09 UTC
I followed all of the instructions of shopify-node-app and got everything running on ngrok.

I went to the ngrok URL and I entered my shopify store's URL and pressed enter and I get the following message in a blank white page:

HMAC validation failed

This is the URL. I changed the ngrok URL to something else, for obvious reasons.

https://121223266b5.ngrok.io/shopify/auth/callback?code=31324296cb2815ee3797cd29cced0e4f&hmac=9f37452cbaf36756e22427f84814828fb7cfc9f550f8a9e7cd8ffddb73058bff&shop=webhutofficial.myshopify.com&timestamp=1535518655

**Comment by sam-cnet** [comment] 2018-09-03 05:00
Hi just wanted to take a stab and say it's likely your app secret that needs updating in your .env file.

**Comment by blakel11** [comment] 2018-09-06 19:00
I am having the same problem. I have done this without using Shopify's boilerplate. It means the issue is with https://github.com/Shopify/shopify-express as this handles the hmac.

**Comment by blakel11** [comment] 2018-09-06 19:27
@RoadToCode822 Good news. You have to update node most likely, nvm install 10.9.

Then go to package-lock.json and update the version of upath to 1.1 everywhere, remove the hash it will be wrong under upath["resolved"].
<img width="676" alt="screen shot 2018-09-06 at 12 26 31 pm" src="https://user-images.githubusercontent.com/4556267/45180402-25c85500-b1d0-11e8-87b2-4b9845621ef7.png">

**Comment by nwtn** [comment] 2019-05-31 14:35
Closing because this project is now deprecated.

**Closed by nwtn** 2019-05-31 14:35 UTC
